require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml
  - base_rubocop.yml

Layout/MultilineOperationIndentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'bin/codeclimate-rubocop'

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NotToNot:
  Enabled: false
