inherit_from: base_rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rails

Style/FileName:
  Exclude:
    - 'bin/codeclimate-rubocop'

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false
