Lint/AmbiguousOperator: 50_000
Lint/AmbiguousRegexpLiteral: 50_000
Lint/AssignmentInCondition: 50_000
Lint/BlockAlignment: 50_000
Lint/CircularArgumentReference: 100_000
Lint/ConditionPosition: 50_000
Lint/Debugger: 50_000
Lint/DefEndAlignment: 50_000
Lint/DeprecatedClassMethods: 50_000
Lint/DuplicateMethods: 100_000
Lint/EachWithObjectArgument: 100_000
Lint/ElseLayout: 50_000
Lint/EmptyEnsure: 50_000
Lint/EmptyInterpolation: 50_000
Lint/EndAlignment: 50_000
Lint/EndInMethod: 50_000
Lint/EnsureReturn: 50_000
Lint/Eval: 500_000
Lint/FormatParameterMismatch: 50_000
Lint/HandleExceptions: 400_000
Lint/InvalidCharacterLiteral: 50_000
Lint/LiteralInCondition: 50_000
Lint/LiteralInInterpolation: 50_000
Lint/Loop: 50_000
Lint/NestedMethodDefinition: 100_000
Lint/NonLocalExitFromIterator: 150_000
Lint/ParenthesesAsGroupedExpression: 50_000
Lint/RequireParentheses: 50_000
Lint/RescueException: 500_000
Lint/ShadowingOuterLocalVariable: 100_000
Lint/SpaceBeforeFirstArg: 50_000
Lint/StringConversionInInterpolation: 50_000
Lint/UnderscorePrefixedVariableName: 50_000
Lint/UnneededDisable: 50_000
Lint/UnreachableCode: 150_000
Lint/UnusedBlockArgument: 50_000
Lint/UnusedMethodArgument: 50_000
Lint/UselessAccessModifier: 50_000
Lint/UselessAssignment: 100_000
Lint/UselessComparison: 100_000
Lint/UselessElseWithoutRescue: 50_000
Lint/UselessSetterCall: 100_000
Lint/Void: 50_000
Metrics/AbcSize: 300_000 + ROUNDUP(observed - max) * 50_000
Metrics/BlockNesting: 500_000
Metrics/ClassLength: ROUND(10 * observed / max) * 100_000
Metrics/CyclomaticComplexity: 300_000 + (observed - max) * 150_000
Metrics/LineLength: 50_000
Metrics/MethodLength: ROUND(10 * observed / max) * 50_000
Metrics/ModuleLength: ROUND(10 * observed / max) * 150_000
Metrics/ParameterLists: 500_000
Metrics/PerceivedComplexity: 300_000 + (observed - max) * 100_000
Performance/Count: 50_000
Performance/Detect: 50_000
Performance/FlatMap: 50_000
Performance/ReverseEach: 50_000
Performance/Sample: 50_000
Performance/Size: 50_000
Performance/StringReplacement: 50_000
Rails/ActionFilter: 50_000
Rails/Date: 100_000
Rails/DefaultScope: 50_000
Rails/Delegate: 50_000
Rails/FindBy: 50_000
Rails/FindEach: 50_000
Rails/HasAndBelongsToMany: 250_000
Rails/Output: 100_000
Rails/ReadWriteAttribute: 50_000
Rails/ScopeArgs: 50_000
Rails/TimeZone: 100_000
Rails/Validation: 50_000
Style/AccessModifierIndentation: 50_000
Style/AccessorMethodName: 100_000
Style/Alias: 50_000
Style/AlignArray: 50_000
Style/AlignHash: 50_000
Style/AlignParameters: 50_000
Style/AndOr: 50_000
Style/ArrayJoin: 50_000
Style/AsciiComments: 50_000
Style/AsciiIdentifiers: 100_000
Style/Attr: 50_000
Style/BarePercentLiterals: 50_000
Style/BeginBlock: 50_000
Style/BlockComments: 50_000
Style/BlockDelimiters: 50_000
Style/BlockEndNewline: 50_000
Style/BracesAroundHashParameters: 50_000
Style/CaseEquality: 50_000
Style/CaseIndentation: 50_000
Style/CharacterLiteral: 50_000
Style/ClassAndModuleCamelCase: 100_000
Style/ClassAndModuleChildren: 50_000
Style/ClassCheck: 50_000
Style/ClassMethods: 50_000
Style/ClassVars: 100_000
Style/ClosingParenthesisIndentation: 50_000
Style/CollectionMethods: 50_000
Style/ColonMethodCall: 50_000
Style/CommandLiteral: 50_000
Style/CommentAnnotation: 50_000
Style/CommentIndentation: 50_000
Style/ConstantName: 50_000
Style/DefWithParentheses: 50_000
Style/DeprecatedHashMethods: 50_000
Style/Documentation: 150_000
Style/DotPosition: 50_000
Style/DoubleNegation: 50_000
Style/EachWithObject: 100_000
Style/ElseAlignment: 50_000
Style/EmptyElse: 50_000
Style/EmptyLineBetweenDefs: 50_000
Style/EmptyLines: 50_000
Style/EmptyLinesAroundAccessModifier: 50_000
Style/EmptyLinesAroundBlockBody: 50_000
Style/EmptyLinesAroundClassBody: 50_000
Style/EmptyLinesAroundMethodBody: 50_000
Style/EmptyLinesAroundModuleBody: 50_000
Style/EmptyLiteral: 50_000
Style/Encoding: 50_000
Style/EndBlock: 50_000
Style/EndOfLine: 50_000
Style/EvenOdd: 50_000
Style/ExtraSpacing: 50_000
Style/FileName: 100_000
Style/FirstParameterIndentation: 50_000
Style/FlipFlop: 100_000
Style/For: 50_000
Style/FormatString: 50_000
Style/GlobalVars: 150_000
Style/GuardClause: 100_000
Style/HashSyntax: 50_000
Style/IfUnlessModifier: 50_000
Style/IfWithSemicolon: 50_000
Style/IndentArray: 50_000
Style/IndentationConsistency: 50_000
Style/IndentationWidth: 50_000
Style/IndentHash: 50_000
Style/InfiniteLoop: 50_000
Style/InitialIndentation: 50_000
Style/InlineComment: 50_000
Style/Lambda: 50_000
Style/LambdaCall: 50_000
Style/LeadingCommentSpace: 50_000
Style/LineEndConcatenation: 50_000
Style/MethodCalledOnDoEndBlock: 150_000
Style/MethodCallParentheses: 50_000
Style/MethodDefParentheses: 50_000
Style/MethodName: 50_000
Style/ModuleFunction: 50_000
Style/MultilineBlockChain: 100_000
Style/MultilineBlockLayout: 50_000
Style/MultilineIfThen: 50_000
Style/MultilineOperationIndentation: 50_000
Style/MultilineTernaryOperator: 50_000
Style/NegatedIf: 50_000
Style/NegatedWhile: 50_000
Style/NestedTernaryOperator: 50_000
Style/Next: 50_000
Style/NilComparison: 50_000
Style/NonNilCheck: 50_000
Style/Not: 50_000
Style/NumericLiterals: 50_000
Style/OneLineConditional: 50_000
Style/OpMethod: 50_000
Style/OptionalArguments: 50_000
Style/ParallelAssignment: 50_000
Style/ParenthesesAroundCondition: 50_000
Style/PercentLiteralDelimiters: 50_000
Style/PercentQLiterals: 50_000
Style/PerlBackrefs: 50_000
Style/PredicateName: 100_000
Style/Proc: 50_000
Style/RaiseArgs: 50_000
Style/RedundantBegin: 50_000
Style/RedundantException: 50_000
Style/RedundantReturn: 50_000
Style/RedundantSelf: 50_000
Style/RegexpLiteral: 50_000
Style/RescueEnsureAlignment: 50_000
Style/RescueModifier: 100_000
Style/SelfAssignment: 50_000
Style/Semicolon: 50_000
Style/SignalException: 50_000
Style/SingleLineBlockParams: 50_000
Style/SingleLineMethods: 50_000
Style/SingleSpaceBeforeFirstArg: 50_000
Style/SpaceAfterColon: 50_000
Style/SpaceAfterComma: 50_000
Style/SpaceAfterControlKeyword: 50_000
Style/SpaceAfterMethodName: 50_000
Style/SpaceAfterNot: 50_000
Style/SpaceAfterSemicolon: 50_000
Style/SpaceAroundBlockParameters: 50_000
Style/SpaceAroundEqualsInParameterDefault: 50_000
Style/SpaceAroundOperators: 50_000
Style/SpaceBeforeBlockBraces: 50_000
Style/SpaceBeforeComma: 50_000
Style/SpaceBeforeComment: 50_000
Style/SpaceBeforeModifierKeyword: 50_000
Style/SpaceBeforeSemicolon: 50_000
Style/SpaceInsideBlockBraces: 50_000
Style/SpaceInsideBrackets: 50_000
Style/SpaceInsideHashLiteralBraces: 50_000
Style/SpaceInsideParens: 50_000
Style/SpaceInsideRangeLiteral: 50_000
Style/SpaceInsideStringInterpolation: 50_000
Style/SpecialGlobalVars: 50_000
Style/StringLiterals: 50_000
Style/StringLiteralsInInterpolation: 50_000
Style/StructInheritance: 100_000
Style/SymbolArray: 50_000
Style/SymbolLiteral: 50_000
Style/SymbolProc: 50_000
Style/Tab: 50_000
Style/TrailingBlankLines: 50_000
Style/TrailingComma: 50_000
Style/TrailingUnderscoreVariable: 50_000
Style/TrailingWhitespace: 50_000
Style/TrivialAccessors: 100_000
Style/UnlessElse: 100_000
Style/UnneededCapitalW: 50_000
Style/UnneededPercentQ: 50_000
Style/UnneededPercentX: 50_000
Style/VariableInterpolation: 50_000
Style/VariableName: 50_000
Style/WhenThen: 50_000
Style/WhileUntilDo: 50_000
Style/WhileUntilModifier: 50_000
Style/WordArray: 50_000
